# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField(default=0, unique=True)),
                ('itemName', models.CharField(max_length=128)),
                ('itemDescription', models.CharField(max_length=512, unique=True)),
                ('itemDatePosted', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerID', models.IntegerField(default=0, unique=True)),
                ('message', models.CharField(max_length=256)),
                ('offerTimeStamp', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='OfferContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.IntegerField(default=0, unique=True)),
                ('sessionName', models.CharField(max_length=32)),
                ('xCords', models.IntegerField(default=0)),
                ('yCords', models.IntegerField(default=0)),
                ('sessionStart', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sessionEnd', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('participants', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=12, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('userPhoneNumber', models.IntegerField(default=0)),
                ('userDescription', models.CharField(max_length=512, unique=True)),
                ('userInterests', models.CharField(max_length=512, unique=True)),
                ('userStartDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sessionparticipants',
            name='participantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='sessionparticipants',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Session'),
        ),
        migrations.AddField(
            model_name='offercontent',
            name='calleeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_side_inventory', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='offercontent',
            name='callerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_side_inventory', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='offercontent',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Item'),
        ),
        migrations.AddField(
            model_name='offercontent',
            name='offerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='fromID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_maker', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='toID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_reciever', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='item',
            name='currentOwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_entitlement', to='market.UserProfile'),
        ),
        migrations.AddField(
            model_name='item',
            name='posterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owns_physically', to='market.UserProfile'),
        ),
    ]
