# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180302_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='currentOwnerId',
            new_name='claimantID',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='posterID',
            new_name='possessorID',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
