# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180302_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionparticipants',
            old_name='sessionId',
            new_name='sessionID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDescription',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionName',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(blank=True, default='Anon', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userDescription',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userInterests',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
