# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180312_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userName',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDatePosted',
            field=models.CharField(default=b'<built-in method today of type object at 0x000000005F82F310>', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userStartDate',
            field=models.CharField(default=b'<built-in method today of type object at 0x000000005F82F310>', max_length=15),
        ),
    ]
