# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180311_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
