# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='claimantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owns_entitlement', to='market.UserProfile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='possessorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_physically', to='market.UserProfile'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='fromID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_maker', to='market.UserProfile'),
        ),
    ]
