# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20180315_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='claimantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_entitlement', to='market.UserProfile'),
        ),
    ]
