# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20180315_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='claimantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owns_entitlement', to='market.UserProfile'),
        ),
        migrations.AlterField(
            model_name='offercontent',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item'),
        ),
        migrations.AlterField(
            model_name='sessionparticipants',
            name='participantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.UserProfile'),
        ),
    ]
