# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20180315_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/media/cat.jpg', upload_to=market.models.user_profile_path),
        ),
    ]
