# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='/media/cat.jpg', upload_to=market.models.item_picture_path),
        ),
    ]
